export type WorkspaceKey =
  | 'overview'
  | 'patient'
  | 'doctor'
  | 'discovery'
  | 'consultation'
  | 'billing'
  | 'clinical'
| 'operations'
| 'analytics'
| 'appointments'
  | 'notifications'
  | 'profile'
  | 'settings'
  | 'admin'
| 'gdpr'
| 'support'
| 'research'
