export type WorkspaceKey =
  | 'overview'
  | 'patient'
  | 'doctor'
  | 'discovery'
  | 'consultation'
  | 'billing'
  | 'clinical'
  | 'operations'
  | 'appointments'
  | 'profile'
  | 'settings'
  | 'admin'
  | 'gdpr'
  | 'research'
